### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by neobrain**
I found no other documentation on this tool, so I had to dig into the source to figure out which network port to whitelist. Having this readme should save others (and future me) the trouble of finding this information.

### CODE REVIEW

**Comment by neobrain** [comment]
On second look at main.c, should the readme say both UDP **and** TCP?

~~Also, I still seem to have trouble getting port forwarding from within Docker to work. Are there any non-obvious ports used by 3dslink other than 17491?~~

EDIT: As usual with these things, the answer reveals itself a couple of minutes after stating the question in public: I was using 3dslink in broadcast mode (i.e. without pointing it to the 3DS's IP address). My guess is Docker's forwarding mechanism doesn't support broadcasting. Using 3dslink with the `-a` switch works perfectly :)

**Comment by WinterMute** [comment]
You could try starting the container with --network=host which I think should allow broadcast to work. The docker default bridge network  has it's own subnet, iirc, and broadcast packets won't cross subnet boundaries.

**Comment by neobrain** [comment]
Fantastic, using `--network=host` gets broadcasting working indeed! :tada:

**Comment by neobrain** [comment]
Is the patch fine other than that? Anything you'd like to see changed?

**Pull request closed without merging**
